version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432" # host:container
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
volumes:
  data: